# fly.toml app configuration file generated for remix-shadcn-starter on 2024-01-07T11:48:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-shadcn-starter"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
